name: Development 

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: [abc-dev]

    strategy:
      matrix:
        node-version: [16.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
 #       cache: 'npm'
    - run: npm i
    - run: CI=false npm run build